services:
  - type: web
    name: news-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
